/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : File
 #	author : miyako
 #	2015/11/01
 #
 # --------------------------------------------------------------------------------*/



// --- File
void FILE_Get_id(sLONG_PTR *pResult, PackagePtr pParams);
void FILE_Get_path(sLONG_PTR *pResult, PackagePtr pParams);
